server:
  port: 8080

spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:h2:mem:restaurantdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
